version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./data/nginx/conf.d:/etc/nginx/conf.d
     - ./data/nginx/powers.jordanpowers.link:/var/www/powers.jordanpowers.link
     - ./data/certbot/conf:/etc/letsencrypt
